# =========================================
# Globals
# =========================================
[globals]
    email = "admin@example.com"
    cmd = "certonly"
    renewal_cron = "0 0 0,12 * * *"

# =========================================
# Certificates
# =========================================
[[certificate]]
    domains = ["example.com", "www.example.com"]
    authenticator = "webroot"
    webroot_path = "/var/www/acme-challenge"

[[certificate]]
    domains = ["my-domain.duckdns.org"]
    authenticator = "dns-duckdns"
    duckdns_token = "123456-78910"
    dns_propagation_seconds = "60"
    args = "--vvv --nginx"